name: Github Pages

on:
  [workflow_dispatch]
env:
  PROJECT_NAME: Blazor.FullCalendar
  OUTPUT_DIR: 'net7.0'
  NETCORE_VERSION: '7.0.x'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up .NET Core SDK ${{ env.NETCORE_VERSION }}...
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      - name: Publish Sample Site
        run: dotnet publish -c Release samples/BlazorWebAssembly/BlazorWebAssembly.csproj
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: samples/BlazorWebAssembly/bin/Release/$OUTPUT_DIR/publish/wwwroot/index.html
          base_href: /${{ env.PROJECT_NAME }}/
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: $GITHUB_TOKEN
          BASE_BRANCH: main # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: samples/BlazorWebAssembly/bin/Release/$OUTPUT_DIR/publish/wwwroot # The folder the action should deploy.
          SINGLE_COMMIT: true
      
      
